{
 "title": "Interactive Drift Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "mlflow_prediction_accuracy",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mlflow_prediction_accuracy" }
   ]
  },
  {
   "title": "model_mse",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_mse" }
   ]
  },
  {
   "title": "target_drift_over_time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mlflow_target_drift_over_time" }
   ]
  },
  {
   "title": "model_r2_score",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_r2_score" }
   ]
  },
  {
   "title": "drift_over_time_conds",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mlflow_feature_drift_over_time{feature=\"conds\"}"
    }
   ]
  },
  {
   "title": "drift_over_time_hum",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mlflow_feature_drift_over_time{feature=\"hum\"}"
    }
   ]
  },
  {
   "title": "drift_over_time_pressurem",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mlflow_feature_drift_over_time{feature=\"pressurem\"}"
    }
   ]
  },
  {
   "title": "drift_over_time_wdird",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mlflow_feature_drift_over_time{feature=\"wdird\"}"
    }
   ]
  },
  {
   "title": "drift_over_time_wdire",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mlflow_feature_drift_over_time{feature=\"wdire\"}\r"
    }
   ]
  },
  {
   "title": "drift_over_time_dewptm",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mlflow_feature_drift_over_time{feature=\"dewptm\"}\r"
    }
   ]
  }
 ]
}